steps:
#- name: 'gcr.io/cloud-builders/go'
#  entrypoint: 'make'
#   args: ['test']
- name: 'gcr.io/cloud-builders/go'
  args: ['build']
  env: ['PROJECT_ROOT=github.com/frodenas/stackdriver_exporter']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/stackdriver-exporter:0.5.1-1', '-t', 'eu.gcr.io/$PROJECT_ID/stackdriver-exporter:latest', '.' ]
images:
- 'eu.gcr.io/$PROJECT_ID/stackdriver-exporter:latest'
- 'eu.gcr.io/$PROJECT_ID/stackdriver-exporter:0.5.1-1'
